source-file ~/.config/tmux/conf/options.conf
source-file ~/.config/tmux/conf/keys.conf
source-file ~/.config/tmux/conf/copy.conf
source-file ~/.config/tmux/conf/agents.conf
source-file ~/.config/tmux/conf/sidebar.conf
source-file ~/.config/tmux/conf/plugins.conf
