set -g set-clipboard on
if-shell "command -v pbcopy" "set -s copy-command pbcopy" \
  { if-shell "command -v wl-copy" "set -s copy-command wl-copy" "set -s copy-command 'xclip -i -selection clipboard'" }

bind Enter copy-mode
bind y run -b "tmux save-buffer - | #{copy-command}"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line

set -g mouse on
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel
bind -T copy-mode-vi WheelUpPane send -X -N3 scroll-up
bind -T copy-mode-vi WheelDownPane send -X -N3 scroll-down
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send -X select-word \; send -X copy-pipe
bind -T copy-mode-vi TripleClick1Pane select-pane \; send -X select-line \; send -X copy-pipe
bind -n DoubleClick1Pane if -F -t = "#{mouse_any_flag}" { send -M } { select-pane -t = ; copy-mode ; send -X select-word ; send -X copy-pipe }
bind -n TripleClick1Pane if -F -t = "#{mouse_any_flag}" { send -M } { select-pane -t = ; copy-mode ; send -X select-line ; send -X copy-pipe }
