set -g default-terminal "tmux-256color"
set -su terminal-overrides
set -su terminal-features
set -as terminal-features "xterm*:RGB:extkeys"
set -s extended-keys on
set -s escape-time 10
set -s focus-events on
set -g allow-passthrough on

set -g history-limit 100000
set -g status-keys vi
set -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
setw -g aggressive-resize on
set -g renumber-windows on
set -g set-titles on
set -g detach-on-destroy off

set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 5

set -g monitor-activity off
