set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-features "xterm*:extkeys"
set -s extended-keys on
set -s escape-time 10
set -s focus-events on
set -g allow-passthrough on

set -g history-limit 100000
set -g status-keys vi
set -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on

set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 5

set -g monitor-activity on
set -g visual-activity off
